<a href="https://colab.research.google.com/github/Mohamed-derbeli/Object-Oriented-Programming__Python/blob/main/OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Lunch:
    def __init__(self,menu):
        self.menu=menu
    def menu_price(self):
        if self.menu == "menu 1":
            print("your choice: ", self.menu, "Price 12.00")
        elif self.menu == "menu 2":
            print("your choice,", self.menu,"Price 13.40" )
        else:
            print("Error in menu")

Reuslt=Lunch("menu 2")
print(Reuslt.menu_price())

your choice, menu 2 Price 13.40
None


In [ ]:
class Point3D:
    def __init__(self,x,y,z):
        self.x=x
        self.y=y
        self.z=z
    def __repr__(self):
        return (self.x, self.y, self.z)

my_point=Point3D(1,2,3)
print (my_point.__repr__())

(1, 2, 3)


In [ ]:
class songs:
    def __init__(self, lyrics):
        self.lyrics=lyrics
    def sing_me_a_song(self):
        for element in self.lyrics:
            print(element)


each_element=songs("Mohamed")
happy_bday=songs(["may god bless you,",
                  "have a sunshine on you,",
                  "happy birthday to yoiu!"])
print(each_element.sing_me_a_song())
print(happy_bday.sing_me_a_song())
#print(each_element.lyrics)

M
o
h
a
m
e
d
None
may god bless you,
have a sunshine on you,
happy birthday to yoiu!
None


In [ ]:
class triangle:
    def __init__(self,angle1, angle2, angle3):
        self.angle1=angle1
        self.angle2=angle2
        self.angle3=angle3
        self.number_of_sides=3

    def check_angles(self):
        result=" "
        sum=self.angle1 + self.angle2 + self.angle3
        if  sum== 180:
            result= True
        else:
            result= False
        return result

my_triangle=triangle(50,110,20)
print(my_triangle.number_of_sides)
print(my_triangle.check_angles())

3
True


In [ ]:
class Question:
  def __init__( self, prompt, answer):
    self.prompt = prompt
    self.answer= answer


question_prompts= [
                  "What color are apples? \n(a) Red/Green \n (b) Purple \n (c) Orange \n \n  ",
                  "What color are Banana? \n(a) Teal \n (b) Magenta \n (c) Yellow \n \n  ",
                  "What color are Limon? \n(a) Green \n (b) Yellow \n (c) Blue \n \n  "
]


questions = [
            Question(question_prompts[0], "a"),
            Question(question_prompts[1], "c"),
            Question(question_prompts[2], "b"), 
]


def run_test(questions):
  score=0
  for question in questions:
    answer = input(question.prompta) 
    if answer== question.answer:
      score += 1
  print("You got " + str(score) + "/" + str(len(questions)) + " acorrect")


run_test(questions)

What color are apples? 
(a) Red/Green 
 (b) Purple 
 (c) Orange 
 
  a
What color are Banana? 
(a) Teal 
 (b) Magenta 
 (c) Yellow 
 
  a
What color are Limon? 
(a) Green 
 (b) Yellow 
 (c) Blue 
 
  a
You got 1/3 acorrect


In [ ]:
class student:
  def __init__(self, name, major, gpa):
    self.name= name
    self.major= major
    self.gpa= gpa


  def on_honor_roll(self):
    if self.gpa >= 3.5:
      return True
    else:
      return False


student1= student("oscar", "Accounting", 3.2)
student2= student("Alex", "Buisness", 3.9)


print(student1.on_honor_roll())
print(student2.on_honor_roll())

False
True


## Inheritance

In [ ]:
class chef1:
  def make_chicken(self):
    print("The chef makes a chicken")
  def make_pizza(self):
    print("The chef makes a pizza")

class chef2:
  def make_salad(self):
    print("The chef makes a salad")
  def make_fried_rice(self):
    print("The chef makes a fried rice")

class general_chef(chef1,chef2):  # inheritence is the process of using functions of other classes
  def make_special_dish(self):
    print("The chef makes a special dish")

mychef=general_chef()

mychef.make_pizza()
mychef.make_fried_rice()

The chef makes a pizza
The chef makes a fried rice


In [ ]:
# Create a child class Bus that will inherit all of the variables and methods of the Vehicle class
# Vehicle Name: School Volvo Speed: 180 Mileage: 12

class Vehicle:
    color= 'White'
    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage
    
class bus(Vehicle):
    def __init__(self):
        Vehicle.__init__(self, 180, 12)
    
    def _Name_(self, name):
        self.name= name
    
    def seating_capacity(self, capacity):
      self.capacity = capacity
      return f'The seating capacity of a {self.name} is {capacity} passengers'

class car(Vehicle):
    pass
    
school_bus= bus()

school_bus._Name_('School Volvo')
print("Color: ", school_bus.color, ", Vehicle Name: ", school_bus.name,", speed: ", school_bus.max_speed, ", Mileage: ", school_bus.mileage)
print(school_bus.seating_capacity(50))


mycar= car(120,12)
print("Color: ", mycar.color, ", speed: ", mycar.max_speed, ", Mileage: ", mycar.mileage)


Color:  White , Vehicle Name:  School Volvo , speed:  180 , Mileage:  12
The seating capacity of a School Volvo is 50 passengers
Color:  White , speed:  120 , Mileage:  12


In [65]:
# Rotate an image/marix by 90 degrees (clockwise).
import numpy as np

def rotate(A):
  n=len(A)
  B=np.zeros((n,n))
  for i in range(n):
      for j in range(n):
        B[i][j]=A[n-j-1][i]
  return B

A=[[1, 2, 3],
   [4, 5, 6],
   [7, 8,9]]
med=rotate(A)
print(A,"\n",med)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
 [[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]


In [75]:
def maxSubArray(A):
    n = len(A)
    maximum=0
    for i in range(n):
        new_max1 =A[i]
        new_max2 =A[n-i-1]
        for j in range(i+1,n):
            new_max1 +=A[j]
            new_max2 +=A[n-j-1]
            new_max = max(new_max1,new_max2)
        if maximum<new_max:
            maximum=new_max          
    return maximum


A = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
   
med=maxSubArray(A)
print(A,"\n",med)

[-2, 1, -3, 4, -1, 2, 1, -5, 4] 
 5


In [33]:
import numpy as np

def setZeroes(A):
    M=len(A)
    N = len(A[0])
    B = np.zeros((M,N),dtype=int)
    A1=np.ones((M,N),dtype=int)
    for i in range(M):
        for j in range(N):
            if A[i][j]==0:
                A1[:][j]= B[:][j]
                A1[i][:]= B[i][:]
                # print(A)
    return A1

A=[[1, 0, 1],
   [1, 1, 1],
   [1, 1, 1]]

output = setZeroes(A)
output

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])