<a href="https://colab.research.google.com/github/Mohamed-derbeli/Object-Oriented-Programming__Python/blob/main/OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Lunch:
    def __init__(self,menu):
        self.menu=menu
    def menu_price(self):
        if self.menu == "menu 1":
            print("your choice: ", self.menu, "Price 12.00")
        elif self.menu == "menu 2":
            print("your choice,", self.menu,"Price 13.40" )
        else:
            print("Error in menu")

Reuslt=Lunch("menu 2")
print(Reuslt.menu_price())

your choice, menu 2 Price 13.40
None


In [ ]:
class Point3D:
    def __init__(self,x,y,z):
        self.x=x
        self.y=y
        self.z=z
    def __repr__(self):
        return (self.x, self.y, self.z)

my_point=Point3D(1,2,3)
print (my_point.__repr__())

(1, 2, 3)


In [ ]:
class songs:
    def __init__(self, lyrics):
        self.lyrics=lyrics
    def sing_me_a_song(self):
        for element in self.lyrics:
            print(element)


each_element=songs("Mohamed")
happy_bday=songs(["may god bless you,",
                  "have a sunshine on you,",
                  "happy birthday to yoiu!"])
print(each_element.sing_me_a_song())
print(happy_bday.sing_me_a_song())
#print(each_element.lyrics)

M
o
h
a
m
e
d
None
may god bless you,
have a sunshine on you,
happy birthday to yoiu!
None


In [ ]:
class triangle:
    def __init__(self,angle1, angle2, angle3):
        self.angle1=angle1
        self.angle2=angle2
        self.angle3=angle3
        self.number_of_sides=3

    def check_angles(self):
        result=" "
        sum=self.angle1 + self.angle2 + self.angle3
        if  sum== 180:
            result= True
        else:
            result= False
        return result

my_triangle=triangle(50,110,20)
print(my_triangle.number_of_sides)
print(my_triangle.check_angles())

3
True


In [ ]:
class Question:
  def __init__( self, prompt, answer):
    self.prompt = prompt
    self.answer= answer


question_prompts= [
                  "What color are apples? \n(a) Red/Green \n (b) Purple \n (c) Orange \n \n  ",
                  "What color are Banana? \n(a) Teal \n (b) Magenta \n (c) Yellow \n \n  ",
                  "What color are Limon? \n(a) Green \n (b) Yellow \n (c) Blue \n \n  "
]


questions = [
            Question(question_prompts[0], "a"),
            Question(question_prompts[1], "c"),
            Question(question_prompts[2], "b"), 
]


def run_test(questions):
  score=0
  for question in questions:
    answer = input(question.prompta) 
    if answer== question.answer:
      score += 1
  print("You got " + str(score) + "/" + str(len(questions)) + " acorrect")


run_test(questions)

What color are apples? 
(a) Red/Green 
 (b) Purple 
 (c) Orange 
 
  a
What color are Banana? 
(a) Teal 
 (b) Magenta 
 (c) Yellow 
 
  a
What color are Limon? 
(a) Green 
 (b) Yellow 
 (c) Blue 
 
  a
You got 1/3 acorrect


In [ ]:
class student:
  def __init__(self, name, major, gpa):
    self.name= name
    self.major= major
    self.gpa= gpa


  def on_honor_roll(self):
    if self.gpa >= 3.5:
      return True
    else:
      return False


student1= student("oscar", "Accounting", 3.2)
student2= student("Alex", "Buisness", 3.9)


print(student1.on_honor_roll())
print(student2.on_honor_roll())

False
True


## Inheritance

In [ ]:
class chef1:
  def make_chicken(self):
    print("The chef makes a chicken")
  def make_pizza(self):
    print("The chef makes a pizza")

class chef2:
  def make_salad(self):
    print("The chef makes a salad")
  def make_fried_rice(self):
    print("The chef makes a fried rice")

class general_chef(chef1,chef2):  # inheritence is the process of using functions of other classes
  def make_special_dish(self):
    print("The chef makes a special dish")

mychef=general_chef()

mychef.make_pizza()
mychef.make_fried_rice()

The chef makes a pizza
The chef makes a fried rice


In [ ]:
# Create a child class Bus that will inherit all of the variables and methods of the Vehicle class
# Vehicle Name: School Volvo Speed: 180 Mileage: 12

class Vehicle:
    color= 'White'
    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage
    
class bus(Vehicle):
    def __init__(self):
        Vehicle.__init__(self, 180, 12)
    
    def _Name_(self, name):
        self.name= name
    
    def seating_capacity(self, capacity):
      self.capacity = capacity
      return f'The seating capacity of a {self.name} is {capacity} passengers'

class car(Vehicle):
    pass
    
school_bus= bus()

school_bus._Name_('School Volvo')
print("Color: ", school_bus.color, ", Vehicle Name: ", school_bus.name,", speed: ", school_bus.max_speed, ", Mileage: ", school_bus.mileage)
print(school_bus.seating_capacity(50))


mycar= car(120,12)
print("Color: ", mycar.color, ", speed: ", mycar.max_speed, ", Mileage: ", mycar.mileage)


Color:  White , Vehicle Name:  School Volvo , speed:  180 , Mileage:  12
The seating capacity of a School Volvo is 50 passengers
Color:  White , speed:  120 , Mileage:  12


In [ ]:
# Rotate an image/marix by 90 degrees (clockwise).
import numpy as np

def rotate(A):
  n=len(A)
  B=np.zeros((n,n))
  for i in range(n):
      for j in range(n):
        B[i][j]=A[n-j-1][i]
  return B

A=[[1, 2, 3],
   [4, 5, 6],
   [7, 8,9]]
med=rotate(A)
print(A,"\n",med)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
 [[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]


In [ ]:
def maxSubArray(A):
    n = len(A)
    maximum=0
    for i in range(n):
        new_max1 =A[i]
        new_max2 =A[n-i-1]
        for j in range(i+1,n):
            new_max1 +=A[j]
            new_max2 +=A[n-j-1]
            new_max = max(new_max1,new_max2)
        if maximum<new_max:
            maximum=new_max          
    return maximum


A = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
   
med=maxSubArray(A)
print(A,"\n",med)

[-2, 1, -3, 4, -1, 2, 1, -5, 4] 
 5


In [ ]:
# if one element in a matrix equal to zero, then replace the whole row and columns of that element to zeros
import numpy as np


A=[[1, 0, 1,0],
   [1, 1, 1,1],
   [1, 1, 1,1]]

def column_zero(A, j):
  A1= []
  for rwo in A:
    rwo[j]= 0
    A1.append(rwo)
  return A1


def setZeroes(A):
    M=len(A)
    N = len(A[0])
    A2=np.ones((M,N),dtype=int)
    for i in range(M):
        for j in range(N):
            if A[i][j]==0:
                A2= column_zero(A2,j)
                A2[i][:]= 0
    return A2



output = setZeroes(A)
output

[array([0, 0, 0, 0]), array([1, 0, 1, 0]), array([1, 0, 1, 0])]

### Math

In [ ]:
# Rearrange a given array so that Arr[i] becomes Arr[Arr[i]] with O(1) extra space.
def arrange( A):
    B=[]
    for i in range(len(A)):
        B.append(A[A[i]])
    return B

A = [ 4, 0, 2, 1, 3 ]

print(arrange(A))

[3, 4, 2, 0, 1]


In [ ]:
# Given an integer n
# The first fibonacci number F1 = 1
# The second fibonacci number F2 = 1
# The n^th fibonacci number Fn = Fn-1 + Fn-2 (n > 2)


def solve(A):
    F=[]
    for i in range(A):
        if i < 2:
            F.append(1)
            print(F)
        else:
            F.append(F[i-1]+F[i-2])
            print(F)
    return F[A-1]

print(solve(10))

[1]
[1, 1]
[1, 1, 2]
[1, 1, 2, 3]
[1, 1, 2, 3, 5]
[1, 1, 2, 3, 5, 8]
[1, 1, 2, 3, 5, 8, 13]
[1, 1, 2, 3, 5, 8, 13, 21]
[1, 1, 2, 3, 5, 8, 13, 21, 34]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
55


### Binary Search

In [ ]:
def sqrt(A):
  if A<0:
    return
  else:
    return int(A**(0.5))

print(sqrt(11)) 

3


In [ ]:
# Array rotation

def rotateArray1(A,d):
  n = len(A)
  A1 = []
  A2 = A
  for i in range(d,n):
    A1.append(A[i])
  
  i = 0
  for i in range(d):
    A1.append(A[i])
  return A1
A = [ 4, 0, 2, 1, 3 ]
print(" Array after left rotation is: ", rotateArray1(A,2))


#____second method___
def rotateArray2(A,d):
  n = len(A)
  A[:] = A[d:n] + A[0:d]
  return A
A = [ 4, 0, 2, 1, 3 ]
print(" Array after left rotation is: ", rotateArray2(A,3)) 

 Array after left rotation is:  [2, 1, 3, 4, 0]
 Array after left rotation is:  [1, 3, 4, 0, 2]


In [ ]:
# Calculate number of rotations

def nb_rotations(A,B):
  n = len(A)
  d=1
  for i in range(n-1,-1,-1):
    if B[i] != A[0]:
      d +=1
    elif B[i] == A[0] and i == 0:
      d = 0
    elif B[i] == A[0]:
       break

  return d


A = [ 4, 0, 2, 1, 3 ]
B = [1, 3, 4, 0, 2]
print(" Array after left rotation is: ", nb_rotations(A,B)) 

 Array after left rotation is:  3


In [ ]:
# searchc an integer B in an array A
def searchIntger(A,B):
  n = len(A)
  temp = []
  for i in range(n):
    if A[i] == B:
      temp = i
      break
    else:
      temp = -1 
  return temp


A = [ 4, 0, 2, 1, 3 ]
B = 1
print(" Array after left rotation is: ", searchIntger(A,B)) 




 Array after left rotation is:  3


In [2]:
# 2D Spiral Array
# Example: n=4
# 01 02 03 04
# 12 13 14 05
# 11 16 15 06
# 10 09 08 07

def spiralArray(n):
  matrix = [[0 for colm in range(n)] for row in range(n)]
  k1=0
  k2=0
  r1=0
  r2=0
  count= 1

  while (k1+k2<n and r1+r2<n):
    # print the first row  
    for i in range(k1,n-k2):
      matrix[k1][i] = count
      count +=1
    r1 +=1  
    #print the last column
    for j in range(r1,n-r2-1):
      matrix[j][n-k2-1]= count
      count +=1
    k2 +=1
    #print the last row 
    for i in range(n-k2,k1,-1):
      matrix[n-r2-1][i]= count
      count +=1
    r2 +=1
    #print the first column
    for j in range(n-r2,r1-1,-1):
      matrix[j][k1]= count
      count +=1
    k1 +=1
  return matrix





my_matrix =spiralArray(10)
for i in my_matrix:
  print(i, "\n")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

[36, 37, 38, 39, 40, 41, 42, 43, 44, 11] 

[35, 64, 65, 66, 67, 68, 69, 70, 45, 12] 

[34, 63, 84, 85, 86, 87, 88, 71, 46, 13] 

[33, 62, 83, 96, 97, 98, 89, 72, 47, 14] 

[32, 61, 82, 95, 100, 99, 90, 73, 48, 15] 

[31, 60, 81, 94, 93, 92, 91, 74, 49, 16] 

[30, 59, 80, 79, 78, 77, 76, 75, 50, 17] 

[29, 58, 57, 56, 55, 54, 53, 52, 51, 18] 

[28, 27, 26, 25, 24, 23, 22, 21, 20, 19] 



In [ ]:
# Look and Say
# 1
# 11
# 21
# 1211
# 111221
# 312211
# 13112221
# 1113213211
# 31131211131221
# 13211311123113112211

def look_and_say(number):
  result = ""
  times= 1
  actual=number[0]
  number= number[1:]+ " "
  for item in number:
    if item!=actual:
      result += str(times)+ actual
      times = 1
      actual = item 
    else:
      times +=1
  return result


number = '1'

for i in range(10):
  print(number)
  number= look_and_say(number)


1
11
21
1211
111221
312211
13112221
1113213211
31131211131221
13211311123113112211


In [25]:
# Edit Distance

# Write a function that returns whether two words are exactly "one edit" away using the following signature:

# bool OneEditApart(string s1, string s2);
# An edit is:
# Inserting one character anywhere in the word (including at the beginning and end)
# Removing one character
# Replacing one character

# Examples:
# OneEditApart("cat", "dog") = false
# OneEditApart("cat", "cats") = true
# OneEditApart("cat", "cut") = true
# OneEditApart("cat", "cast") = true
# OneEditApart("cat", "at") = true
# OneEditApart("cat", "act") = false

def OneEditApart(s1,s2):
  m = len(s1)
  n = len(s2)

  if (abs(m-n)>1):
    return False
  
  edit = 0
  i = 0
  j = 0
  while i<m and j<n:
    if s1[i]!=s2[j]:
      edit +=1
      if edit>1:
        return False
      if m>n:
        i +=1
      elif m<n:
        j +=1
      else:
        i+=1
        j+=1
    else:
      i+=1
      j+=1
  
  
  if i==m and j==n:
    if edit==1:
      return True
    else:
      return False

print(OneEditApart("cat", "cut"))

True


### Linked Lists

In [41]:
# You are given two linked lists representing two non-negative numbers. The digits are stored in reverse order
#  and each of their nodes contain a single digit. Add the two numbers and return it as a linked list.
# Input: (2 -> 4 -> 3) + (5 -> 6 -> 4)
# Output: 7 -> 0 -> 8
#     342 + 465 = 807
# Make sure there are no trailing zeros in the output list
# So, 7 -> 0 -> 8 -> 0 is not a valid response even though the value is still 807.
def addTwoNumbers(A, B):
  print(A,B)
  A= str(A)
  B= str(B)
  n = len(A)
  m = len(B)
  New_A=[]
  New_B=[]
  New_result=[]
  for i in range(n-1,-1,-1):
    New_A.append(A[i])
  str1 = ''.join(str(e) for e in New_A)
  for j in range(m-1,-1,-1):
    New_B.append(B[j])
  str2 = ''.join(str(e) for e in New_B) 
  result= int(str1) + int(str2)
  
  print(f'The sum of {int(str1)} + {int(str2)} = {result}')
  
  result= str(result)
  for item in range(len(result)-1,-1,-1):
    New_result.append(result[item])

  return New_result


print(addTwoNumbers(523,278))




523 278
The sum of 325 + 872 = 1197
['7', '9', '1', '1']


In [50]:
class ListNode:
    def __init__(self, x):
        self.val = x
        self.next = None

class Solution:
    def addTwoNumbers(self, A, B):
        a, b = A, B
        head = ListNode(0)
        cur_sum = head
        while a != None or b != None or cur_sum.val > 9:
            carry = cur_sum.val / 10
            cur_sum.val %= 10
            a_val = 0 if a == None else a.val
            b_val = 0 if b == None else b.val
            next_val = a_val + b_val + carry
            cur_sum.next = ListNode(next_val)
            cur_sum = cur_sum.next
            a = None if a == None else a.next
            b = None if b == None else b.next
        return head.next


# k=Solution()
# k.addTwoNumbers(A,B)




# class Node:

#     def __init__(self, data):
#         self.data = data
#         self.next = None
def addTwoLists(self, first, second):
    prev = None
    temp = None
    carry = 0
    while first is not None or second is not None:
        if first is None:
            firstData = 0
        else:
            firstData = first.data
        if second is None:
            secondData = 0
        else:
            secondData = second.data
        Sum = carry
        Sum += firstData
        Sum += secondData
        if Sum >= 10:
            carry = 1
        else:
            carry = 0
        Sum %= 10
        temp = Node(Sum)
        if self.head is None:
            self.head = temp
        else:
            prev.next = temp
        prev = temp
        if first is not None:
            first = first.next
        if second is not None:
            second = second.next
    if carry > 0:
        temp.next = Node(carry)

In [5]:
# Reverse a linked list from position m to n. Do it in-place and in one-pass.
# For example:
# Given 1->2->3->4->5->NULL, m = 2 and n = 4,
# return 1->4->3->2->5->NULL.
# Note:
# Given m, n satisfy the following condition:
# 1 ≤ m ≤ n ≤ length of list.
# Note 2:
# Usually the version often seen in the interviews is reversing the whole linked list which is obviously an easier version of this question.


def reverseBetween(A, B, C):


  if 

SyntaxError: ignored